-- Nomeia as Colorações Específicas (match por codigoLegado).

UPDATE "Servico" SET nome='Despigmentação' WHERE "codigoLegado"=24;
UPDATE "Servico" SET nome='Alcian Blue' WHERE "codigoLegado"=25;
UPDATE "Servico" SET nome='Fontana Masson' WHERE "codigoLegado"=26;
UPDATE "Servico" SET nome='Giemsa' WHERE "codigoLegado"=27;
UPDATE "Servico" SET nome='Gram BH/BB' WHERE "codigoLegado"=28;
UPDATE "Servico" SET nome='Grocott' WHERE "codigoLegado"=29;
UPDATE "Servico" SET nome='Mucicarmin' WHERE "codigoLegado"=30;
UPDATE "Servico" SET nome='Pams' WHERE "codigoLegado"=31;
UPDATE "Servico" SET nome='PAS' WHERE "codigoLegado"=32;
UPDATE "Servico" SET nome='Pas c Alcian Blue' WHERE "codigoLegado"=33;
UPDATE "Servico" SET nome='Pas c/Diastase' WHERE "codigoLegado"=34;
UPDATE "Servico" SET nome='Pelrs (Azul da Prússia)' WHERE "codigoLegado"=35;
UPDATE "Servico" SET nome='Picrossírius' WHERE "codigoLegado"=36;
UPDATE "Servico" SET nome='Reticulina' WHERE "codigoLegado"=37;
UPDATE "Servico" SET nome='Rodanina' WHERE "codigoLegado"=38;
UPDATE "Servico" SET nome='Sudan Black' WHERE "codigoLegado"=39;
UPDATE "Servico" SET nome='Tricômico de Masson' WHERE "codigoLegado"=40;
UPDATE "Servico" SET nome='Verhoeff' WHERE "codigoLegado"=41;
UPDATE "Servico" SET nome='Vermelho Congo' WHERE "codigoLegado"=42;
UPDATE "Servico" SET nome='Von Kossa' WHERE "codigoLegado"=43;
UPDATE "Servico" SET nome='Ziehl Nilsen' WHERE "codigoLegado"=44;
UPDATE "Servico" SET nome='Azul de Toluidina' WHERE "codigoLegado"=59;
UPDATE "Servico" SET nome='Resorcina' WHERE "codigoLegado"=78;
UPDATE "Servico" SET nome='colorações - Diversas' WHERE "codigoLegado"=122;
UPDATE "Servico" SET nome='Ferro Coloidal' WHERE "codigoLegado"=148;
UPDATE "Servico" SET nome='Coloração de Luna' WHERE "codigoLegado"=175;
UPDATE "Servico" SET nome='Prata de Jones' WHERE "codigoLegado"=195;
UPDATE "Servico" SET nome='Coloração específica trazendo lamina T. Masson' WHERE "codigoLegado"=292;
UPDATE "Servico" SET nome='Alcian Blue com Pas' WHERE "codigoLegado"=299;
UPDATE "Servico" SET nome='Sudan Black trazendo lamina' WHERE "codigoLegado"=316;
UPDATE "Servico" SET nome='Violeta Cresil c Corante cliente' WHERE "codigoLegado"=381;
UPDATE "Servico" SET nome='Tricomico de Masson fornecendo lamina c corte' WHERE "codigoLegado"=382;
UPDATE "Servico" SET nome='Sudan + Az Toluidina' WHERE "codigoLegado"=655;
UPDATE "Servico" SET nome='Oil Red' WHERE "codigoLegado"=713;
UPDATE "Servico" SET nome='Alzarin Red' WHERE "codigoLegado"=776;
UPDATE "Servico" SET nome='Gomori' WHERE "codigoLegado"=834;
UPDATE "Servico" SET nome='Azul de metileno' WHERE "codigoLegado"=835;
UPDATE "Servico" SET nome='Warthin Starry' WHERE "codigoLegado"=845;
UPDATE "Servico" SET nome='Safranina' WHERE "codigoLegado"=903;
UPDATE "Servico" SET nome='HE com Alcian Blue' WHERE "codigoLegado"=932;
UPDATE "Servico" SET variante1='Contra-corado com hematoxilina', variante2='Não Contra-corado' WHERE "codigoLegado"=36;
