-- Nomeia os Insumos/Materiais (match por codigoLegado).

UPDATE "Servico" SET nome='Caixa porta lâminas 50 Unidades', variante1='Cx' WHERE "codigoLegado"=46;
UPDATE "Servico" SET nome='Caixa porta lâmina 25 unidades', variante1='Cx' WHERE "codigoLegado"=47;
UPDATE "Servico" SET nome='Caixa porta lâmina 100 unidades', variante1='Cx' WHERE "codigoLegado"=48;
UPDATE "Servico" SET nome='Cassetes histológicos - 500 Un.', variante1='Pct' WHERE "codigoLegado"=50;
UPDATE "Servico" SET nome='Cassetes Histológicos - 100 und', variante1='Pct' WHERE "codigoLegado"=67;
UPDATE "Servico" SET nome='Descalcificador 500ML', variante1='ML' WHERE "codigoLegado"=68;
UPDATE "Servico" SET nome='Cassetes Histológicos - 250 Und', variante1='Pct' WHERE "codigoLegado"=82;
UPDATE "Servico" SET nome='Hematoxilina Harris 500ml', variante1='ML' WHERE "codigoLegado"=91;
UPDATE "Servico" SET nome='Eosina 500ml', variante1='ML' WHERE "codigoLegado"=92;
UPDATE "Servico" SET nome='Formol 10% 50ml', variante1='ML' WHERE "codigoLegado"=97;
UPDATE "Servico" SET nome='Formol 10% 1L', variante1='ML' WHERE "codigoLegado"=98;
UPDATE "Servico" SET nome='Frasco de formol com 50 ml', variante1='ML' WHERE "codigoLegado"=107;
UPDATE "Servico" SET nome='Cx. com 50 un.de laminas Silanizadas', variante1='Cx' WHERE "codigoLegado"=112;
UPDATE "Servico" SET nome='FORMOL 37%', variante1='ML' WHERE "codigoLegado"=135;
UPDATE "Servico" SET nome='Cx. de lâmina Lapidada Fosca com 50 Un', variante1='Cx' WHERE "codigoLegado"=137;
UPDATE "Servico" SET nome='Cx. de lâmina polarizada com 70 un.', variante1='Cx' WHERE "codigoLegado"=142;
UPDATE "Servico" SET nome='Cx. de Lamínula 24x32', variante1='Cx' WHERE "codigoLegado"=143;
UPDATE "Servico" SET nome='Cx. de Lamínula 24x40', variante1='Cx' WHERE "codigoLegado"=144;
UPDATE "Servico" SET nome='Cx. de Lamínula 24x50', variante1='Cx' WHERE "codigoLegado"=145;
UPDATE "Servico" SET nome='Cx. de Lamínula 24x60', variante1='Cx' WHERE "codigoLegado"=146;
UPDATE "Servico" SET nome='caixa de lâmina carga positiva com 50 un.', variante1='Cx' WHERE "codigoLegado"=161;
UPDATE "Servico" SET nome='Descalcificador 1Lt', variante1='ML' WHERE "codigoLegado"=166;
UPDATE "Servico" SET nome='ÁGUA DESTILADA 5 LTS', variante1='ML' WHERE "codigoLegado"=206;
UPDATE "Servico" SET nome='Tubo para 3 laminas', variante1='Unidade' WHERE "codigoLegado"=225;
UPDATE "Servico" SET nome='Alcool Absoluto', variante1='ML' WHERE "codigoLegado"=256;
UPDATE "Servico" SET nome='BANDEJA PORTA LAMINAS C/ 20 POSICOES', variante1='peça' WHERE "codigoLegado"=259;
UPDATE "Servico" SET nome='Meio de montagem', variante1='ML' WHERE "codigoLegado"=277;
UPDATE "Servico" SET nome='NAVALHA DESCARTÁVEL COM 50 UN.', variante1='Cx' WHERE "codigoLegado"=280;
UPDATE "Servico" SET nome='Caixa de lamínula 24x32 com 100 un', variante1='Cx' WHERE "codigoLegado"=285;
UPDATE "Servico" SET nome='Caixa de lamínula 24x50', variante1='Cx' WHERE "codigoLegado"=286;
UPDATE "Servico" SET nome='Caixa de lamínula 24x60 com 100 un', variante1='Cx' WHERE "codigoLegado"=287;
UPDATE "Servico" SET nome='NAVALHA DESCARTÁVEL', variante1='Unidade' WHERE "codigoLegado"=323;
UPDATE "Servico" SET nome='Eosina solução alcoólica - Lt', variante1='ML' WHERE "codigoLegado"=334;
UPDATE "Servico" SET nome='Caixa de laminas lapidada fosca', variante1='Cx' WHERE "codigoLegado"=358;
UPDATE "Servico" SET nome='Caixa para armazenamento de blocos', variante1='Cx' WHERE "codigoLegado"=363;
UPDATE "Servico" SET nome='Caixa de lminas silanizadas com 50 unidades', variante1='Cx' WHERE "codigoLegado"=365;
UPDATE "Servico" SET nome='Cassetes Histológicos 250 un', variante1='Pct' WHERE "codigoLegado"=378;
UPDATE "Servico" SET nome='XILOL 1LT', variante1='ML' WHERE "codigoLegado"=523;
UPDATE "Servico" SET nome='Frasco de formol 10% 20 ml', variante1='ML' WHERE "codigoLegado"=533;
UPDATE "Servico" SET nome='Descalcificados 250ML', variante1='ML' WHERE "codigoLegado"=663;
UPDATE "Servico" SET nome='Formol tamponado 10% 1L', variante1='ML' WHERE "codigoLegado"=709;
UPDATE "Servico" SET nome='Giemsa Corante Merck 1 lt', variante1='ML' WHERE "codigoLegado"=847;
UPDATE "Servico" SET nome='HD externo Usb 3.0', variante1='Unidade' WHERE "codigoLegado"=902;
