export const SERVICOS_LEGADO = [
  { codigo: '1', codigoLegado: 1, categoria: 'Processamento', nome: 'HE Processamento inclusão + HE (cassetes identificados)', precoRotina: 8.8, precoPesquisa: 9.9 },
  { codigo: '2', codigoLegado: 2, categoria: 'Cortes Histológico', nome: 'Processamento inclusão e corte s/ coloração', precoRotina: 9.0, precoPesquisa: 9.0 },
  { codigo: '5', codigoLegado: 5, categoria: 'Processamento', nome: 'Processamento e inclusão', precoRotina: 8.5, precoPesquisa: 9.9 },
  { codigo: '7', codigoLegado: 7, categoria: 'Citologia', nome: 'Coloração de HE em citologia', precoRotina: 3.5, precoPesquisa: 3.5 },
  { codigo: '8', codigoLegado: 8, categoria: 'Colorações', nome: 'Descoloração de lâmina', precoRotina: 6.0, precoPesquisa: 8.0 },
  { codigo: '10', codigoLegado: 10, categoria: 'Macroscopia', nome: 'Descalcificação da amostra', precoRotina: 6.0, precoPesquisa: 7.0 },
  { codigo: '12', codigoLegado: 12, categoria: 'Citologia', nome: 'Centrifugação com 2 lâminas de esfregaço', precoRotina: 14.5, precoPesquisa: 14.5 },
  { codigo: '13', codigoLegado: 13, categoria: 'Citologia', nome: 'Citocentrifugação (Citospin) em 1 lâminas', precoRotina: 8.0, precoPesquisa: 8.0 },
  { codigo: '14', codigoLegado: 14, categoria: 'Citologia', nome: 'Centrifugação mais emblocado (Cell block)', precoRotina: 17.0, precoPesquisa: 17.0 },
  { codigo: '17', codigoLegado: 17, categoria: 'Criostato', nome: 'Corte em lam. silanizada  1 lamina da amostra + HE', precoRotina: 33.0, precoPesquisa: 35.0 },
  { codigo: '18', codigoLegado: 18, categoria: 'Criostato', nome: 'Corte lâminas silanizadas acima de 2 lamina por amostra', precoRotina: 23.0, precoPesquisa: 25.0 },
  { codigo: '23', codigoLegado: 23, categoria: 'Citologia', nome: 'Coloração e Leitura de Citologia Convencional', precoRotina: 16.0, precoPesquisa: 16.0 },
  { codigo: '24', codigoLegado: 24, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '25', codigoLegado: 25, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '26', codigoLegado: 26, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '27', codigoLegado: 27, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '28', codigoLegado: 28, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '29', codigoLegado: 29, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '30', codigoLegado: 30, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '31', codigoLegado: 31, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '32', codigoLegado: 32, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '33', codigoLegado: 33, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '34', codigoLegado: 34, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '35', codigoLegado: 35, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '36', codigoLegado: 36, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '37', codigoLegado: 37, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '38', codigoLegado: 38, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '39', codigoLegado: 39, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '40', codigoLegado: 40, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 20.0 },
  { codigo: '41', codigoLegado: 41, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '42', codigoLegado: 42, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '43', codigoLegado: 43, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '44', codigoLegado: 44, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '45', codigoLegado: 45, categoria: 'Macroscopia', nome: '2 amostra', precoRotina: 15.4, precoPesquisa: 19.0 },
  { codigo: '46', codigoLegado: 46, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '47', codigoLegado: 47, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '48', codigoLegado: 48, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '49', codigoLegado: 49, categoria: 'Cortes Histológico', nome: 'Corte histológico em lâminas c Carga Positiva', precoRotina: 7.0, precoPesquisa: 7.0 },
  { codigo: '50', codigoLegado: 50, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '53', codigoLegado: 53, categoria: 'Imunofluorescência', nome: 'Serviço técnico de congelação', precoRotina: 180.0, precoPesquisa: 180.0 },
  { codigo: '54', codigoLegado: 54, categoria: 'Análises', nome: 'Análise ativação microglial', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '58', codigoLegado: 58, categoria: 'Processamento', nome: 'Processamento urgente', precoRotina: 25.0, precoPesquisa: 30.0 },
  { codigo: '59', codigoLegado: 59, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '67', codigoLegado: 67, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '68', codigoLegado: 68, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '69', codigoLegado: 69, categoria: 'Macroscopia', nome: 'Simples 3 amostras', precoRotina: 14.3, precoPesquisa: 17.0 },
  { codigo: '73', codigoLegado: 73, categoria: 'Análises', nome: 'Análise Citológica 1-Nódulo', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '75', codigoLegado: 75, categoria: 'Criostato', nome: 'Corte em lam. polarizada  1 lamina da amostra + HE', precoRotina: 35.0, precoPesquisa: 38.0 },
  { codigo: '76', codigoLegado: 76, categoria: 'Imunohistoquímica', nome: 'Imunohistoquimica c/ Anticorpo Histocell', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '78', codigoLegado: 78, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '82', codigoLegado: 82, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '86', codigoLegado: 86, categoria: 'Criostato', nome: 'Corte em lam. silanizada  1 lamina da amostra', precoRotina: 28.0, precoPesquisa: 30.0 },
  { codigo: '89', codigoLegado: 89, categoria: 'Outros', nome: 'HEs com 2 blocos na mesma lâmina', precoRotina: 15.0, precoPesquisa: 15.0 },
  { codigo: '91', codigoLegado: 91, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '92', codigoLegado: 92, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '93', codigoLegado: 93, categoria: 'Cortes Histológico', nome: 'Corte em eppendorf 4 vezes de 20 micras', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '94', codigoLegado: 94, categoria: 'Cortes Eppendorf', nome: '5 cortes com troca de navalha', precoRotina: 12.0, precoPesquisa: 15.0 },
  { codigo: '97', codigoLegado: 97, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '98', codigoLegado: 98, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '99', codigoLegado: 99, categoria: 'Macroscopia', nome: 'Simples acima 3 amostras', precoRotina: 16.5, precoPesquisa: 19.9 },
  { codigo: '102', codigoLegado: 102, categoria: 'Laudos', nome: 'Laudo Histopatológico', precoRotina: 150.0, precoPesquisa: 150.0 },
  { codigo: '105', codigoLegado: 105, categoria: 'Cortes Histológico', nome: 'Novo HE', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '107', codigoLegado: 107, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '108', codigoLegado: 108, categoria: 'Processamento', nome: 'Processamento', precoRotina: 4.0, precoPesquisa: 5.5 },
  { codigo: '112', codigoLegado: 112, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '117', codigoLegado: 117, categoria: 'Citologia', nome: 'Coloração de Papanicolaou em citologia', precoRotina: 4.5, precoPesquisa: 4.5 },
  { codigo: '122', codigoLegado: 122, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '132', codigoLegado: 132, categoria: 'Citologia', nome: 'Especificas', precoRotina: 6.6, precoPesquisa: 6.6 },
  { codigo: '135', codigoLegado: 135, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '137', codigoLegado: 137, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '139', codigoLegado: 139, categoria: 'Outros', nome: 'Imprint em material congelado', precoRotina: 12.0, precoPesquisa: 12.0 },
  { codigo: '142', codigoLegado: 142, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '143', codigoLegado: 143, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '144', codigoLegado: 144, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '145', codigoLegado: 145, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '146', codigoLegado: 146, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '148', codigoLegado: 148, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '149', codigoLegado: 149, categoria: 'Macroscopia', nome: 'Simples 1 amostra', precoRotina: 8.8, precoPesquisa: 9.9 },
  { codigo: '151', codigoLegado: 151, categoria: 'Macroscopia', nome: '1 amostra', precoRotina: 11.0, precoPesquisa: 13.0 },
  { codigo: '158', codigoLegado: 158, categoria: 'Cortes Histológico', nome: 'Corte em eppendorf com troca de navalha', precoRotina: 14.5, precoPesquisa: 14.5 },
  { codigo: '159', codigoLegado: 159, categoria: 'Cortes Histológico', nome: 'Cortes para Microdissecção à laser', precoRotina: 29.0, precoPesquisa: 29.0 },
  { codigo: '160', codigoLegado: 160, categoria: 'Cortes Histológico', nome: 'Cortes para Microdissecção à laser (3 cortes)', precoRotina: 39.0, precoPesquisa: 39.0 },
  { codigo: '161', codigoLegado: 161, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '166', codigoLegado: 166, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '175', codigoLegado: 175, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '177', codigoLegado: 177, categoria: 'Macroscopia', nome: 'simples processamento e HE sem descrição macroscópica', precoRotina: 14.5, precoPesquisa: 17.5 },
  { codigo: '178', codigoLegado: 178, categoria: 'Macroscopia', nome: 'Intestino (lúmen) processamento e HE', precoRotina: 17.0, precoPesquisa: 19.9 },
  { codigo: '179', codigoLegado: 179, categoria: 'Laudos', nome: 'Laudo Histopatológico', precoRotina: 200.0, precoPesquisa: 200.0 },
  { codigo: '189', codigoLegado: 189, categoria: 'Citologia', nome: 'Frasco para citologia cap. 3 laminas', precoRotina: 4.0, precoPesquisa: 4.0 },
  { codigo: '191', codigoLegado: 191, categoria: 'Processamento', nome: 'Reinclusão da amostra', precoRotina: 5.9, precoPesquisa: 7.0 },
  { codigo: '192', codigoLegado: 192, categoria: 'Cortes Histológico', nome: 'Corte histológico fornecendo lamina', precoRotina: 4.9, precoPesquisa: 4.9 },
  { codigo: '193', codigoLegado: 193, categoria: 'Cortes Histológico', nome: 'Corte em eppendorf 6 vezes de 10 micras', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '195', codigoLegado: 195, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '196', codigoLegado: 196, categoria: 'Cortes Histológico', nome: 'corte em eppendorf de (15) micrômetros', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '202', codigoLegado: 202, categoria: ' Descarte - Devolução', nome: 'Descarte de Formol /material biológico Kg ou LT', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '203', codigoLegado: 203, categoria: 'Imagem', nome: 'FOTOMICROGRAFIA', precoRotina: 17.0, precoPesquisa: 17.0 },
  { codigo: '206', codigoLegado: 206, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '209', codigoLegado: 209, categoria: 'Cortes Histológico', nome: 'Processamento inclusão e corte em lamina silanizada', precoRotina: 9.8, precoPesquisa: 9.8 },
  { codigo: '211', codigoLegado: 211, categoria: 'Macroscopia', nome: 'Material ósseo', precoRotina: 11.0, precoPesquisa: 13.0 },
  { codigo: '212', codigoLegado: 212, categoria: 'Cortes Histológico', nome: 'Reinclusão +corte + HE', precoRotina: 13.9, precoPesquisa: 13.9 },
  { codigo: '215', codigoLegado: 215, categoria: 'Macroscopia', nome: 'Simples 2 amostras', precoRotina: 12.0, precoPesquisa: 14.5 },
  { codigo: '225', codigoLegado: 225, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '227', codigoLegado: 227, categoria: 'Cortes Histológico', nome: 'Corte Histológico com 2 blocos na mesma lamina HE', precoRotina: 12.0, precoPesquisa: 12.0 },
  { codigo: '228', codigoLegado: 228, categoria: 'Cortes Histológico', nome: 'Corte Histologico mais HE', precoRotina: 6.6, precoPesquisa: 6.6 },
  { codigo: '229', codigoLegado: 229, categoria: 'Imagem', nome: 'Scanner Biopsias', precoRotina: 6.5, precoPesquisa: 6.5 },
  { codigo: '230', codigoLegado: 230, categoria: 'Imagem', nome: 'Scanner Peças', precoRotina: 20.0, precoPesquisa: 20.0 },
  { codigo: '231', codigoLegado: 231, categoria: 'Imagem', nome: 'Citologia / Centrifugação', precoRotina: 19.0, precoPesquisa: 19.0 },
  { codigo: '232', codigoLegado: 232, categoria: 'Macroscopia', nome: 'Biópsia', precoRotina: 4.0, precoPesquisa: 5.0 },
  { codigo: '238', codigoLegado: 238, categoria: 'Laudos', nome: 'Laudo histopatológico', precoRotina: 250.0, precoPesquisa: 250.0 },
  { codigo: '256', codigoLegado: 256, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '257', codigoLegado: 257, categoria: 'Macroscopia', nome: 'acima 3 amostra', precoRotina: 18.7, precoPesquisa: 22.0 },
  { codigo: '259', codigoLegado: 259, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '261', codigoLegado: 261, categoria: 'Colorações', nome: 'Corte Histológico seriado + coloração + finalização', precoRotina: 9.9, precoPesquisa: 11.8 },
  { codigo: '265', codigoLegado: 265, categoria: 'Cortes Histológico', nome: 'Corte histológico seriado', precoRotina: 25.0, precoPesquisa: 25.0 },
  { codigo: '266', codigoLegado: 266, categoria: 'Imunohistoquímica', nome: 'Linfonodo Sentinela c/ 2 imunos 3 laminas', precoRotina: 250.0, precoPesquisa: 250.0 },
  { codigo: '270', codigoLegado: 270, categoria: 'Criostato', nome: 'Corte em lam. polarizada  1 lamina da amostra', precoRotina: 30.0, precoPesquisa: 32.0 },
  { codigo: '275', codigoLegado: 275, categoria: 'Processamento', nome: 'Reinclusão para 2 amostras', precoRotina: 12.9, precoPesquisa: 16.0 },
  { codigo: '276', codigoLegado: 276, categoria: 'Processamento', nome: 'Reinclusão para 3 amostras', precoRotina: 15.9, precoPesquisa: 15.9 },
  { codigo: '277', codigoLegado: 277, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '280', codigoLegado: 280, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '282', codigoLegado: 282, categoria: 'Citologia', nome: 'Esfregaço citológico', precoRotina: 3.5, precoPesquisa: 3.5 },
  { codigo: '284', codigoLegado: 284, categoria: 'Imunohistoquímica', nome: 'Imuno PADRONIZAÇÃO', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '285', codigoLegado: 285, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '286', codigoLegado: 286, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '287', codigoLegado: 287, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '292', codigoLegado: 292, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '296', codigoLegado: 296, categoria: 'Cortes Histológico', nome: 'Corte em eppendorf 2 vezes de 50 micras', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '298', codigoLegado: 298, categoria: 'Imunohistoquímica', nome: 'Imunohistoquímica c/ anticorpo do cliente', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '299', codigoLegado: 299, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '302', codigoLegado: 302, categoria: 'Análises', nome: 'Analise do Patologista 3 Lam (HE + 2 complemento)', precoRotina: 120.0, precoPesquisa: 120.0 },
  { codigo: '307', codigoLegado: 307, categoria: 'Imagem', nome: 'Fotos de laminas (pesquisa)', precoRotina: 16.0, precoPesquisa: 16.0 },
  { codigo: '309', codigoLegado: 309, categoria: 'Outros', nome: 'Laminas Ionizadas (Serviço refeito)', precoRotina: 3.2, precoPesquisa: 3.2 },
  { codigo: '311', codigoLegado: 311, categoria: 'Outros', nome: 'Linfonodo Sentinela c/ 3 laminas de HE e laminas Polarizada', precoRotina: 42.0, precoPesquisa: 42.0 },
  { codigo: '316', codigoLegado: 316, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '317', codigoLegado: 317, categoria: 'Análises', nome: 'Analise do Patologista 4 Lam (HE + 3 complemento)', precoRotina: 140.0, precoPesquisa: 140.0 },
  { codigo: '318', codigoLegado: 318, categoria: 'Análises', nome: 'Analise do Patologista 6 Lam (HE + 5 complemento)', precoRotina: 170.0, precoPesquisa: 170.0 },
  { codigo: '319', codigoLegado: 319, categoria: 'Análises', nome: 'Analise do Patologista acima 6 Lam (HE + complemento)', precoRotina: 180.0, precoPesquisa: 180.0 },
  { codigo: '321', codigoLegado: 321, categoria: 'Outros', nome: 'Lamina controle H. Pilory', precoRotina: 10.0, precoPesquisa: 10.0 },
  { codigo: '323', codigoLegado: 323, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '325', codigoLegado: 325, categoria: 'Processamento', nome: 'Reprocessamento e reinclusão da amostra', precoRotina: 9.9, precoPesquisa: 12.0 },
  { codigo: '334', codigoLegado: 334, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '339', codigoLegado: 339, categoria: ' Descarte - Devolução', nome: 'Devolução de bloco', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '340', codigoLegado: 340, categoria: ' Descarte - Devolução', nome: 'Devolução de orgão', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '344', codigoLegado: 344, categoria: 'Consultoria/Serviços', nome: 'Hora técnica', precoRotina: 49.0, precoPesquisa: 49.0 },
  { codigo: '353', codigoLegado: 353, categoria: 'Macroscopia', nome: 'simples processamento e inclusão sem descrição macroscópica', precoRotina: 12.0, precoPesquisa: 14.5 },
  { codigo: '358', codigoLegado: 358, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '363', codigoLegado: 363, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '365', codigoLegado: 365, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '366', codigoLegado: 366, categoria: 'Cortes Histológico', nome: 'Corte Histológico com 2 blocos na mesma lamina', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '371', codigoLegado: 371, categoria: 'Macroscopia', nome: 'Simples peças radicais acima 5 quilos simples peças radicais acima 5 quilos', precoRotina: 25.2, precoPesquisa: 31.0 },
  { codigo: '372', codigoLegado: 372, categoria: 'Macroscopia', nome: 'Necro', precoRotina: 16.0, precoPesquisa: 19.0 },
  { codigo: '374', codigoLegado: 374, categoria: 'Macroscopia', nome: 'Descrião de biopsia com medida', precoRotina: 5.0, precoPesquisa: 6.0 },
  { codigo: '375', codigoLegado: 375, categoria: 'Macroscopia', nome: 'Peça radical Baço membro lobo hep pulmão rim', precoRotina: 20.0, precoPesquisa: 24.0 },
  { codigo: '376', codigoLegado: 376, categoria: 'Citologia', nome: 'Coloração de Panotico em Citologia/Esfregaço', precoRotina: 5.0, precoPesquisa: 5.0 },
  { codigo: '378', codigoLegado: 378, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '381', codigoLegado: 381, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '382', codigoLegado: 382, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '383', codigoLegado: 383, categoria: 'Citologia', nome: 'Centrifugação mais emblocado (Cell block) mais lamina Cito', precoRotina: 20.0, precoPesquisa: 20.0 },
  { codigo: '385', codigoLegado: 385, categoria: 'Cortes Histológico', nome: 'Corte histológico em lâminas Silanizadas Branca', precoRotina: 5.9, precoPesquisa: 5.9 },
  { codigo: '387', codigoLegado: 387, categoria: 'Processamento', nome: 'Processamento e inclusão em cassete 7 X 5 X 2 mais HE', precoRotina: 22.0, precoPesquisa: 26.0 },
  { codigo: '388', codigoLegado: 388, categoria: 'Anticorpo', nome: 'AE1/AE3 ANTI CORPO HISTOCELL', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '389', codigoLegado: 389, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente AE1/AE3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '390', codigoLegado: 390, categoria: 'Colorações', nome: 'Coloração de HE', precoRotina: 3.0, precoPesquisa: 4.0 },
  { codigo: '397', codigoLegado: 397, categoria: 'Cortes Histológico', nome: 'Corte histologico mais HE e finalização', precoRotina: 7.7, precoPesquisa: 7.7 },
  { codigo: '398', codigoLegado: 398, categoria: 'Cortes Histológico', nome: 'Corte histológico 3º nivel', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '399', codigoLegado: 399, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell AE1/AE3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '400', codigoLegado: 400, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Bcl 2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '401', codigoLegado: 401, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BRST-2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '402', codigoLegado: 402, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Ca 19.9', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '403', codigoLegado: 403, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Calretinina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '404', codigoLegado: 404, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 10', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '405', codigoLegado: 405, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 15', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '406', codigoLegado: 406, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 23', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '407', codigoLegado: 407, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 30', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '408', codigoLegado: 408, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 43', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '409', codigoLegado: 409, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 56', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '410', codigoLegado: 410, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 7', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '411', codigoLegado: 411, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD5', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '413', codigoLegado: 413, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CEA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '414', codigoLegado: 414, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Alk 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '415', codigoLegado: 415, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Bcl 6', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '417', codigoLegado: 417, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Calponina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '418', codigoLegado: 418, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CAM 5.2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '419', codigoLegado: 419, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 138', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '420', codigoLegado: 420, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 20', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '422', codigoLegado: 422, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 31', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '423', codigoLegado: 423, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 45LCA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '424', codigoLegado: 424, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 68', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '425', codigoLegado: 425, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 99', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '426', codigoLegado: 426, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CDX2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '428', codigoLegado: 428, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CK 5/6', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '429', codigoLegado: 429, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CK20', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '430', codigoLegado: 430, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Cromogranina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '431', codigoLegado: 431, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell EMA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '432', codigoLegado: 432, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Gata 3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '433', codigoLegado: 433, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Glicoforina A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '435', codigoLegado: 435, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Melan A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '436', codigoLegado: 436, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PAX 8', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '437', codigoLegado: 437, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PSA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '438', codigoLegado: 438, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Synaptofisina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '439', codigoLegado: 439, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Vimentina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '441', codigoLegado: 441, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HHF 35', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '442', codigoLegado: 442, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CK7', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '443', codigoLegado: 443, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Desmina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '444', codigoLegado: 444, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell F VIII', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '445', codigoLegado: 445, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GFAP', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '446', codigoLegado: 446, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Hepatocyte', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '447', codigoLegado: 447, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Inibina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '448', codigoLegado: 448, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MSA (AML)', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '449', codigoLegado: 449, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PAX 5', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '450', codigoLegado: 450, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PS100', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '451', codigoLegado: 451, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PSAP', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '452', codigoLegado: 452, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell TTF1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '453', codigoLegado: 453, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell WT1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '454', codigoLegado: 454, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell p63', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '455', codigoLegado: 455, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Lisozyme', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '456', codigoLegado: 456, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Insulina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '457', codigoLegado: 457, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Enolase', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '458', codigoLegado: 458, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell 34bE12', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '459', codigoLegado: 459, categoria: 'Cortes Histológico', nome: 'Corte histológico em material ósseo + HE', precoRotina: 11.0, precoPesquisa: 11.0 },
  { codigo: '460', codigoLegado: 460, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell KI 67', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '461', codigoLegado: 461, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CSRP3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '462', codigoLegado: 462, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CRP3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '463', codigoLegado: 463, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 1A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '464', codigoLegado: 464, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HBME 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '465', codigoLegado: 465, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GALECTINA 3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '466', codigoLegado: 466, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CK 19', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '467', codigoLegado: 467, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell P53', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '468', codigoLegado: 468, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell RACEMASE', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '469', codigoLegado: 469, categoria: 'IPOG', nome: 'HPV BAIXO RISCO', precoRotina: 150.0, precoPesquisa: 150.0 },
  { codigo: '470', codigoLegado: 470, categoria: 'IPOG', nome: 'HPV ALTO RISCO', precoRotina: 150.0, precoPesquisa: 150.0 },
  { codigo: '471', codigoLegado: 471, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ISOPROSTANO', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '472', codigoLegado: 472, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell S100', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '473', codigoLegado: 473, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell FXIIIa', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '474', codigoLegado: 474, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CICLINA D1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '475', codigoLegado: 475, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HHV8', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '477', codigoLegado: 477, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD79', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '478', codigoLegado: 478, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Citoqueratina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '479', codigoLegado: 479, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell DOG1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '480', codigoLegado: 480, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FATOR 8', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '481', codigoLegado: 481, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MUM-1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '482', codigoLegado: 482, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell LISOZIMA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '483', codigoLegado: 483, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD45RA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '484', codigoLegado: 484, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell E CADERINA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '486', codigoLegado: 486, categoria: 'Análises', nome: 'Analise do Patologista 2 Lam (HE + 1 complemento)', precoRotina: 110.0, precoPesquisa: 110.0 },
  { codigo: '487', codigoLegado: 487, categoria: 'Imunohistoquímica', nome: 'Imuni c Anticorpo Histocell MUM 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '489', codigoLegado: 489, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente USP8', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '490', codigoLegado: 490, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ACTH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '491', codigoLegado: 491, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente 5hmc', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '492', codigoLegado: 492, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell C KIT', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '493', codigoLegado: 493, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '494', codigoLegado: 494, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '495', codigoLegado: 495, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD7', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '496', codigoLegado: 496, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD8', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '499', codigoLegado: 499, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CYP11B1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '500', codigoLegado: 500, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CYP11B2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '501', codigoLegado: 501, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente IBA 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '502', codigoLegado: 502, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente INOS', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '503', codigoLegado: 503, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ARGINASE', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '504', codigoLegado: 504, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD45', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '506', codigoLegado: 506, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HMB45', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '508', codigoLegado: 508, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FAM62c', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '509', codigoLegado: 509, categoria: 'Cortes Eppendorf', nome: '2 cortes de 10 micras', precoRotina: 12.0, precoPesquisa: 15.0 },
  { codigo: '510', codigoLegado: 510, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Actina AML', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '511', codigoLegado: 511, categoria: 'Cortes Histológico', nome: 'Corte histológico 2º nivel', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '512', codigoLegado: 512, categoria: 'Processamento', nome: 'REINCLUSÃO EM CASSETES 7 X 5 X 2', precoRotina: 12.0, precoPesquisa: 15.0 },
  { codigo: '513', codigoLegado: 513, categoria: 'Cortes Histológico', nome: 'Corte histológico 1º nivel', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '514', codigoLegado: 514, categoria: 'Cortes Histológico', nome: 'Corte Histológico com 4 blocos na mesma lamina s coloração', precoRotina: 12.0, precoPesquisa: 12.0 },
  { codigo: '515', codigoLegado: 515, categoria: 'Cortes Histológico', nome: 'Corte Histológico com 5 blocos na mesma lamina s coloração', precoRotina: 15.0, precoPesquisa: 15.0 },
  { codigo: '516', codigoLegado: 516, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '517', codigoLegado: 517, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP8', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '518', codigoLegado: 518, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUM1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '521', codigoLegado: 521, categoria: 'Cortes Histológico', nome: 'Corte histológico para laminas megaslide', precoRotina: 15.0, precoPesquisa: 15.0 },
  { codigo: '523', codigoLegado: 523, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '524', codigoLegado: 524, categoria: 'Colorações', nome: 'Descoloração de lâmina e novo HE', precoRotina: 9.0, precoPesquisa: 11.5 },
  { codigo: '525', codigoLegado: 525, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MIOGENINA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '526', codigoLegado: 526, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD34', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '527', codigoLegado: 527, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente VEGF', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '528', codigoLegado: 528, categoria: 'Cortes Histológico', nome: 'Corte em eppendorf 5 vezes de 10 micras', precoRotina: 9.9, precoPesquisa: 9.9 },
  { codigo: '529', codigoLegado: 529, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Cologeno I', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '530', codigoLegado: 530, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Cologeno III', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '531', codigoLegado: 531, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Cologeno V', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '532', codigoLegado: 532, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL33', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '533', codigoLegado: 533, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '534', codigoLegado: 534, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell alfa SMA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '535', codigoLegado: 535, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TIMP-1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '536', codigoLegado: 536, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente BCL2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '539', codigoLegado: 539, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Receptor Estrogenio', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '540', codigoLegado: 540, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Receptor Progesterona', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '541', codigoLegado: 541, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '542', codigoLegado: 542, categoria: 'Cortes Histológico', nome: 'Cortes Histologico mais HE', precoRotina: 6.6, precoPesquisa: 6.6 },
  { codigo: '544', codigoLegado: 544, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BETA CATENINA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '545', codigoLegado: 545, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente GP91', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '546', codigoLegado: 546, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL17', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '547', codigoLegado: 547, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL4', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '548', codigoLegado: 548, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL6', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '549', codigoLegado: 549, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL10', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '550', codigoLegado: 550, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente TGFB1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '553', codigoLegado: 553, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Receptor de androgeno', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '554', codigoLegado: 554, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Citocromo c', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '555', codigoLegado: 555, categoria: 'Processamento', nome: 'Teste macroscopia mais HE e Papanicolau', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '556', codigoLegado: 556, categoria: 'Criostato', nome: 'Corte lâminas polarizadas Acima de 2 lamina por amostra', precoRotina: 26.0, precoPesquisa: 28.0 },
  { codigo: '557', codigoLegado: 557, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NFKB', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '558', codigoLegado: 558, categoria: 'Imagem', nome: 'Scanner TMA', precoRotina: 13.0, precoPesquisa: 13.0 },
  { codigo: '560', codigoLegado: 560, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HER 2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '561', codigoLegado: 561, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MSH 2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '562', codigoLegado: 562, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MSH 6', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '563', codigoLegado: 563, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MLH 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '564', codigoLegado: 564, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PMS2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '565', codigoLegado: 565, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell TdT', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '566', codigoLegado: 566, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUC 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '568', codigoLegado: 568, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Napsin A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '569', codigoLegado: 569, categoria: 'Processamento', nome: 'Processamento e inclusão em cassete 7 X 5 X 2', precoRotina: 15.0, precoPesquisa: 15.0 },
  { codigo: '570', codigoLegado: 570, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Glucagon', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '571', codigoLegado: 571, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente KI67', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '572', codigoLegado: 572, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Galectina 3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '575', codigoLegado: 575, categoria: 'Processamento', nome: 'Inclusão em parafina', precoRotina: 3.0, precoPesquisa: 4.0 },
  { codigo: '576', codigoLegado: 576, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MOC31', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '578', codigoLegado: 578, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUC 6', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '580', codigoLegado: 580, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUC5A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '583', codigoLegado: 583, categoria: 'Imunofluorescência', nome: 'IF - IgG IgA', precoRotina: 80.0, precoPesquisa: 80.0 },
  { codigo: '584', codigoLegado: 584, categoria: 'Imunofluorescência', nome: 'IF - C3C IgM', precoRotina: 80.0, precoPesquisa: 80.0 },
  { codigo: '585', codigoLegado: 585, categoria: 'Imunofluorescência', nome: 'IF - FiB C1q', precoRotina: 80.0, precoPesquisa: 80.0 },
  { codigo: '586', codigoLegado: 586, categoria: 'Imunofluorescência', nome: 'IF -K/L', precoRotina: 80.0, precoPesquisa: 80.0 },
  { codigo: '587', codigoLegado: 587, categoria: 'Imunofluorescência', nome: 'IF - C4D', precoRotina: 240.0, precoPesquisa: 240.0 },
  { codigo: '588', codigoLegado: 588, categoria: 'Imunofluorescência', nome: 'IF HE', precoRotina: 6.6, precoPesquisa: 6.6 },
  { codigo: '592', codigoLegado: 592, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente H3K4me3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '593', codigoLegado: 593, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente H4K16ac', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '594', codigoLegado: 594, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Baxcl', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '595', codigoLegado: 595, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SDHA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '596', codigoLegado: 596, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SDHB', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '597', codigoLegado: 597, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TIMP-2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '598', codigoLegado: 598, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '599', codigoLegado: 599, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente (Actin H-196)', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '600', codigoLegado: 600, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TFPI (E-20)', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '603', codigoLegado: 603, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell SV40', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '604', codigoLegado: 604, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell C4D', precoRotina: 110.0, precoPesquisa: 110.0 },
  { codigo: '605', codigoLegado: 605, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Receptor Estrogeno Alfa', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '606', codigoLegado: 606, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Receptor Estrogeno Beta', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '607', codigoLegado: 607, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Receptor Androgenio', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '609', codigoLegado: 609, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD 206', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '610', codigoLegado: 610, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Elastase', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '612', codigoLegado: 612, categoria: 'Macroscopia', nome: 'Proc inclusão e corte em lamina s coloração', precoRotina: 12.0, precoPesquisa: 14.0 },
  { codigo: '613', codigoLegado: 613, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD 68', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '614', codigoLegado: 614, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD 11c', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '615', codigoLegado: 615, categoria: 'Macroscopia', nome: 'Vaso (lúmen) processamento e HE', precoRotina: 17.0, precoPesquisa: 19.9 },
  { codigo: '616', codigoLegado: 616, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD8', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '617', codigoLegado: 617, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IgG4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '619', codigoLegado: 619, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL 1B', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '621', codigoLegado: 621, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PLA2R', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '622', codigoLegado: 622, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell VEGF', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '626', codigoLegado: 626, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente OPA 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '627', codigoLegado: 627, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FIS 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '628', codigoLegado: 628, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente DRP 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '629', codigoLegado: 629, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MFN 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '630', codigoLegado: 630, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente LSD 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '631', codigoLegado: 631, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell P16', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '635', codigoLegado: 635, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUC 2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '637', codigoLegado: 637, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '639', codigoLegado: 639, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente GFP', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '641', codigoLegado: 641, categoria: 'Cortes Histológico', nome: 'Corte histológico 4º nivel', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '642', codigoLegado: 642, categoria: 'Cortes Histológico', nome: 'Corte histológico 5º nivel', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '643', codigoLegado: 643, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente RHOT 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '644', codigoLegado: 644, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente RHOT 2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '645', codigoLegado: 645, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente AQUAPORINA-4', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '646', codigoLegado: 646, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BCG', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '649', codigoLegado: 649, categoria: 'Cortes Histológico', nome: 'Corte histológico em resina', precoRotina: 7.9, precoPesquisa: 7.9 },
  { codigo: '650', codigoLegado: 650, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente PCNA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '652', codigoLegado: 652, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente VAT', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '653', codigoLegado: 653, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Toxoplasma', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '654', codigoLegado: 654, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP9', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '655', codigoLegado: 655, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 25.0 },
  { codigo: '656', codigoLegado: 656, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente COX 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '657', codigoLegado: 657, categoria: 'Análises', nome: 'Analise do Patologista 5 Lam (HE + 4 complemento)', precoRotina: 150.0, precoPesquisa: 150.0 },
  { codigo: '658', codigoLegado: 658, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente COX 2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '660', codigoLegado: 660, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ALFA 7', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '661', codigoLegado: 661, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente E CADERINA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '662', codigoLegado: 662, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Caspase 3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '663', codigoLegado: 663, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '664', codigoLegado: 664, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CMV', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '667', codigoLegado: 667, categoria: 'Imagem', nome: 'Foto para fluorescencia rodanina Fluoresceina', precoRotina: 18.0, precoPesquisa: 18.0 },
  { codigo: '668', codigoLegado: 668, categoria: 'Imagem', nome: 'Foto para fluorescencia filtro verde', precoRotina: 10.0, precoPesquisa: 10.0 },
  { codigo: '669', codigoLegado: 669, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ADENOVIRUS', precoRotina: 60.0, precoPesquisa: 60.0 },
  { codigo: '670', codigoLegado: 670, categoria: 'Cortes Histológico', nome: 'Corte histológico com navalha exclusiva para amostra c HE', precoRotina: 25.0, precoPesquisa: 25.0 },
  { codigo: '671', codigoLegado: 671, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NF kb', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '672', codigoLegado: 672, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NRF2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '674', codigoLegado: 674, categoria: 'Anticorpo', nome: 'ANTICORPO ISOLADO', precoRotina: 60.0, precoPesquisa: 60.0 },
  { codigo: '676', codigoLegado: 676, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente VIMENTINA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '677', codigoLegado: 677, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD31', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '678', codigoLegado: 678, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente DECORIN', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '679', codigoLegado: 679, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente BIGLICAN', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '680', codigoLegado: 680, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente VGFA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '681', codigoLegado: 681, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Cox2', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '682', codigoLegado: 682, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente YAP1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '683', codigoLegado: 683, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TLR4', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '684', codigoLegado: 684, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MIOGLOBINA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '685', codigoLegado: 685, categoria: 'Consultoria/Serviços', nome: 'Consultoria técnica', precoRotina: 300.0, precoPesquisa: 300.0 },
  { codigo: '686', codigoLegado: 686, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell OCT 3/4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '687', codigoLegado: 687, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PLAP', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '688', codigoLegado: 688, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell SALL4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '691', codigoLegado: 691, categoria: 'Consultoria/Serviços', nome: 'Consultoria técnica Diagnosticare', precoRotina: 13000.0, precoPesquisa: 13000.0 },
  { codigo: '693', codigoLegado: 693, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente PDCD4', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '694', codigoLegado: 694, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SSTR2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '695', codigoLegado: 695, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ZNF 367', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '696', codigoLegado: 696, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NT5C2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '697', codigoLegado: 697, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FZD6', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '698', codigoLegado: 698, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente GNAQ', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '699', codigoLegado: 699, categoria: 'Anticorpo', nome: 'Anticorpo A4GALT', precoRotina: 6760.0, precoPesquisa: 6760.0 },
  { codigo: '700', codigoLegado: 700, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente A4GALT', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '701', codigoLegado: 701, categoria: 'Anticorpo', nome: 'Anticorpo Caspase 3 100 ul', precoRotina: 8563.89, precoPesquisa: 8563.89 },
  { codigo: '702', codigoLegado: 702, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD11C', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '703', codigoLegado: 703, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 163', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '706', codigoLegado: 706, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ISO', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '708', codigoLegado: 708, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo', precoRotina: 570.0, precoPesquisa: 570.0 },
  { codigo: '709', codigoLegado: 709, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '710', codigoLegado: 710, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell KAPPA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '711', codigoLegado: 711, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell LAMBDA', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '712', codigoLegado: 712, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GRANZIMA B', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '713', codigoLegado: 713, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '714', codigoLegado: 714, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IDH1', precoRotina: 102.0, precoPesquisa: 102.0 },
  { codigo: '715', codigoLegado: 715, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ATRX', precoRotina: 130.0, precoPesquisa: 130.0 },
  { codigo: '716', codigoLegado: 716, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Myo D1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '717', codigoLegado: 717, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '718', codigoLegado: 718, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IgG', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '720', codigoLegado: 720, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MUC 4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '726', codigoLegado: 726, categoria: 'Imunofluorescência', nome: 'IF PLA2R', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '727', codigoLegado: 727, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente EXT 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '729', codigoLegado: 729, categoria: 'Anticorpo', nome: 'Imuno Anti-Chondroitin Sulfate antibody [CS-56]', precoRotina: 8900.0, precoPesquisa: 8900.0 },
  { codigo: '730', codigoLegado: 730, categoria: 'Anticorpo', nome: 'Imuno AntiHyaluronic acid', precoRotina: 8900.0, precoPesquisa: 8900.0 },
  { codigo: '731', codigoLegado: 731, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FXR', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '732', codigoLegado: 732, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ALFA SMA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '733', codigoLegado: 733, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PD 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '736', codigoLegado: 736, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TMA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '738', codigoLegado: 738, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell C MYC', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '739', codigoLegado: 739, categoria: 'Citologia', nome: 'Centrifugação mais emblocado líquido cavitário (Cell block)', precoRotina: 22.0, precoPesquisa: 22.0 },
  { codigo: '740', codigoLegado: 740, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente 5 HIDROXY', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '741', codigoLegado: 741, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MMP12', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '742', codigoLegado: 742, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente TGF', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '743', codigoLegado: 743, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SOD3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '744', codigoLegado: 744, categoria: 'Outros', nome: 'Grupo GREMAR', precoRotina: 23.0, precoPesquisa: 23.0 },
  { codigo: '746', codigoLegado: 746, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SLC25 A11', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '747', codigoLegado: 747, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HSV I', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '748', codigoLegado: 748, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GLUT 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '749', codigoLegado: 749, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell RCC', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '750', codigoLegado: 750, categoria: 'Manutenção', nome: 'Manutenção da Centrifuga Visita', precoRotina: 350.0, precoPesquisa: 350.0 },
  { codigo: '751', codigoLegado: 751, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IBA 1', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '752', codigoLegado: 752, categoria: 'Outros', nome: 'TMA - Até 100 amostras c/ HE', precoRotina: 1500.0, precoPesquisa: 1500.0 },
  { codigo: '753', codigoLegado: 753, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell LH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '754', codigoLegado: 754, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '755', codigoLegado: 755, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell FSH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '756', codigoLegado: 756, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell TSH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '757', codigoLegado: 757, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ACTH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '758', codigoLegado: 758, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Treponema', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '759', codigoLegado: 759, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PRL', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '760', codigoLegado: 760, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MDM2', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '761', codigoLegado: 761, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CDK4', precoRotina: 105.0, precoPesquisa: 105.0 },
  { codigo: '762', codigoLegado: 762, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell H3K27ME', precoRotina: 110.0, precoPesquisa: 110.0 },
  { codigo: '763', codigoLegado: 763, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IgM', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '764', codigoLegado: 764, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente BRCA 2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '765', codigoLegado: 765, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente P53', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '766', codigoLegado: 766, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente PDP2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '767', codigoLegado: 767, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FOSDO P53', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '768', codigoLegado: 768, categoria: 'Outros', nome: 'Desqueratinização', precoRotina: 12.5, precoPesquisa: 12.5 },
  { codigo: '769', codigoLegado: 769, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente RMR1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '776', codigoLegado: 776, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 25.0 },
  { codigo: '778', codigoLegado: 778, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente BCL10', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '779', codigoLegado: 779, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NEFRINA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '780', codigoLegado: 780, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente KLOTHO', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '781', codigoLegado: 781, categoria: 'Colorações', nome: 'Coloração de HE mais finalização', precoRotina: 6.6, precoPesquisa: 7.5 },
  { codigo: '784', codigoLegado: 784, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ERG', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '785', codigoLegado: 785, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Pgp 9.5', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '786', codigoLegado: 786, categoria: 'Outros', nome: 'Laminário com 20 orgãos', precoRotina: 390.0, precoPesquisa: 390.0 },
  { codigo: '787', codigoLegado: 787, categoria: 'Outros', nome: 'Laminário com 41 orgãos', precoRotina: 779.0, precoPesquisa: 779.0 },
  { codigo: '789', codigoLegado: 789, categoria: 'Imunohistoquímica', nome: 'Imunohistoquímica c/ anticorpo do cliente (IF) parafina', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '790', codigoLegado: 790, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente LGR5', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '791', codigoLegado: 791, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Gastrina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '792', codigoLegado: 792, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Colageno IV', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '793', codigoLegado: 793, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Tireoglobulina', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '794', codigoLegado: 794, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ALFA1 ANTITRIP', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '795', codigoLegado: 795, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CHECK2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '796', codigoLegado: 796, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente BRCA2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '797', codigoLegado: 797, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Ki67(SP6)', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '798', codigoLegado: 798, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente beta catenin', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '799', codigoLegado: 799, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD34 EP', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '804', codigoLegado: 804, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Ca 125', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '805', codigoLegado: 805, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell INI 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '806', codigoLegado: 806, categoria: 'Imagem', nome: 'Digitalização de lamina', precoRotina: 20.0, precoPesquisa: 20.0 },
  { codigo: '807', codigoLegado: 807, categoria: 'Cortes Histológico', nome: 'HE processamento intestino (lúmen) corte histologico', precoRotina: 17.5, precoPesquisa: 17.5 },
  { codigo: '809', codigoLegado: 809, categoria: 'Cortes Histológico', nome: 'Corte histológico 3º nivel de 10 micras', precoRotina: 8.8, precoPesquisa: 8.8 },
  { codigo: '811', codigoLegado: 811, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PAX 2', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '812', codigoLegado: 812, categoria: 'Cortes Histológico', nome: 'HE processamento intestino (Arteria) corte histologico', precoRotina: 17.5, precoPesquisa: 17.5 },
  { codigo: '814', codigoLegado: 814, categoria: 'Cortes Histológico', nome: 'Inclusão e corte histológico', precoRotina: 5.9, precoPesquisa: 5.9 },
  { codigo: '815', codigoLegado: 815, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell MIELOPEROXIDASE', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '817', codigoLegado: 817, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell OCT 2', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '819', codigoLegado: 819, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell SURFACTANTE', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '820', codigoLegado: 820, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell EBV', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '822', codigoLegado: 822, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TET-1 + PAS', precoRotina: 54.0, precoPesquisa: 54.0 },
  { codigo: '823', codigoLegado: 823, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TET-1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '824', codigoLegado: 824, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TET-2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '825', codigoLegado: 825, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TET-3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '826', codigoLegado: 826, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente 5HMC', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '827', codigoLegado: 827, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Caspase', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '828', codigoLegado: 828, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Villina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '830', codigoLegado: 830, categoria: 'Anticorpo', nome: 'Linker mouse 01 unidades', precoRotina: 409.76, precoPesquisa: 409.76 },
  { codigo: '833', codigoLegado: 833, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell D2 40', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '834', codigoLegado: 834, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '835', codigoLegado: 835, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '836', codigoLegado: 836, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CMYC', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '840', codigoLegado: 840, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell NEU N', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '841', codigoLegado: 841, categoria: 'Análises', nome: 'Analise / Laudo com foto 1 Lamina', precoRotina: 90.0, precoPesquisa: 90.0 },
  { codigo: '843', codigoLegado: 843, categoria: 'Consultoria/Serviços', nome: 'Consultoria técnica remoto', precoRotina: 150.0, precoPesquisa: 150.0 },
  { codigo: '844', codigoLegado: 844, categoria: 'Consultoria/Serviços', nome: 'Consultoria técnica presencial', precoRotina: 300.0, precoPesquisa: 300.0 },
  { codigo: '845', codigoLegado: 845, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 35.0, precoPesquisa: 40.0 },
  { codigo: '846', codigoLegado: 846, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Actina Alfafetoproteina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '847', codigoLegado: 847, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '848', codigoLegado: 848, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HSV II', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '849', codigoLegado: 849, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 21', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '850', codigoLegado: 850, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell HELICOBACTER', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '852', codigoLegado: 852, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CK17', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '853', codigoLegado: 853, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell TNF-a', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '854', codigoLegado: 854, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell IgD', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '855', codigoLegado: 855, categoria: 'IPOG', nome: 'Hibridização FISH SUBTIPOS HER-2/CEM17', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '858', codigoLegado: 858, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Rest', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '860', codigoLegado: 860, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ORM1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '861', codigoLegado: 861, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente IgG3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '862', codigoLegado: 862, categoria: 'Anticorpo', nome: 'Anticorpo BCL10 - 3ML Dr Fila', precoRotina: 2026.94, precoPesquisa: 2026.94 },
  { codigo: '863', codigoLegado: 863, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NG2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '864', codigoLegado: 864, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Oligodendrócito O1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '865', codigoLegado: 865, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Olig2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '866', codigoLegado: 866, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD11B', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '867', codigoLegado: 867, categoria: 'Anticorpo', nome: 'Anticorpo CD44 ac mono coelho clone ZR 184 1ml', precoRotina: 5893.0, precoPesquisa: 5893.0 },
  { codigo: '868', codigoLegado: 868, categoria: 'Anticorpo', nome: 'Anticorpo laminina ac mono cam clone 4C7 1ml', precoRotina: 8698.17, precoPesquisa: 8698.17 },
  { codigo: '870', codigoLegado: 870, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BRAF', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '871', codigoLegado: 871, categoria: 'Análises', nome: 'Analise de estudos ALS', precoRotina: 60.0, precoPesquisa: 60.0 },
  { codigo: '872', codigoLegado: 872, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL7', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '873', codigoLegado: 873, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente FOXP 3', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '874', codigoLegado: 874, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BEREP4', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '875', codigoLegado: 875, categoria: 'Imagem', nome: 'Scanner de laminas', precoRotina: 14.9, precoPesquisa: 14.9 },
  { codigo: '878', codigoLegado: 878, categoria: 'Imagem', nome: 'Foto lâminas', precoRotina: 25.0, precoPesquisa: 25.0 },
  { codigo: '882', codigoLegado: 882, categoria: 'Citologia', nome: 'Coloração de He ou Papanicolau em citologia', precoRotina: 3.5, precoPesquisa: 3.5 },
  { codigo: '883', codigoLegado: 883, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CD 44', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '884', codigoLegado: 884, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Laminina', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '892', codigoLegado: 892, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente NFL (IF)', precoRotina: 45.0, precoPesquisa: 45.0 },
  { codigo: '893', codigoLegado: 893, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 25', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '894', codigoLegado: 894, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Tryptase A1', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '896', codigoLegado: 896, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente OXTR', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '897', codigoLegado: 897, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente RECEPTOR DE OPIOIDE', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '900', codigoLegado: 900, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell GLYPICAN 3', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '901', codigoLegado: 901, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ARG 1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '902', codigoLegado: 902, categoria: 'Insumos/Materiais', nome: 'Material', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '903', codigoLegado: 903, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 25.0, precoPesquisa: 28.0 },
  { codigo: '904', codigoLegado: 904, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente HIF-1a', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '905', codigoLegado: 905, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ICAM-1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '906', codigoLegado: 906, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente VCAM-1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '907', codigoLegado: 907, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TNF@', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '910', codigoLegado: 910, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell ARGINASE', precoRotina: 95.0, precoPesquisa: 95.0 },
  { codigo: '911', codigoLegado: 911, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Cologeno II', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '912', codigoLegado: 912, categoria: 'Macroscopia', nome: 'Esferoides mais HE', precoRotina: 18.0, precoPesquisa: 22.0 },
  { codigo: '916', codigoLegado: 916, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Calcitonina', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '917', codigoLegado: 917, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo MLH1', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '918', codigoLegado: 918, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo MSH2', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '919', codigoLegado: 919, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo MSH6', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '920', codigoLegado: 920, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo PMS2', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '921', codigoLegado: 921, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo HER 2', precoRotina: 2200.0, precoPesquisa: 2200.0 },
  { codigo: '922', codigoLegado: 922, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo RE', precoRotina: 5280.0, precoPesquisa: 5280.0 },
  { codigo: '923', codigoLegado: 923, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo RP', precoRotina: 4560.0, precoPesquisa: 4560.0 },
  { codigo: '924', codigoLegado: 924, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo KI67', precoRotina: 3840.0, precoPesquisa: 3840.0 },
  { codigo: '925', codigoLegado: 925, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo SINAPTO', precoRotina: 1800.0, precoPesquisa: 1800.0 },
  { codigo: '926', codigoLegado: 926, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo BCG', precoRotina: 2600.0, precoPesquisa: 2600.0 },
  { codigo: '927', codigoLegado: 927, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo AE1 AE3', precoRotina: 1800.0, precoPesquisa: 1800.0 },
  { codigo: '928', codigoLegado: 928, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo CK7', precoRotina: 1800.0, precoPesquisa: 1800.0 },
  { codigo: '929', codigoLegado: 929, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo CROMO', precoRotina: 2100.0, precoPesquisa: 2100.0 },
  { codigo: '930', codigoLegado: 930, categoria: 'Anticorpo', nome: 'Imuno alíquota de BUFFER', precoRotina: 600.0, precoPesquisa: 600.0 },
  { codigo: '932', codigoLegado: 932, categoria: 'Coloração Específica', nome: 'Especificas', precoRotina: 19.8, precoPesquisa: 22.0 },
  { codigo: '936', codigoLegado: 936, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TGF-ß', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '938', codigoLegado: 938, categoria: 'Processamento', nome: 'Reinclusão de 1 amostra transformando em 2 amostras', precoRotina: 15.9, precoPesquisa: 18.0 },
  { codigo: '939', codigoLegado: 939, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo 34 BE12', precoRotina: 1600.0, precoPesquisa: 1600.0 },
  { codigo: '940', codigoLegado: 940, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo Calponin', precoRotina: 1800.0, precoPesquisa: 1800.0 },
  { codigo: '941', codigoLegado: 941, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo ERG', precoRotina: 4200.0, precoPesquisa: 4200.0 },
  { codigo: '942', codigoLegado: 942, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo AML', precoRotina: 3600.0, precoPesquisa: 3600.0 },
  { codigo: '943', codigoLegado: 943, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo Racemase', precoRotina: 4520.0, precoPesquisa: 4520.0 },
  { codigo: '944', codigoLegado: 944, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo P63', precoRotina: 3800.0, precoPesquisa: 3800.0 },
  { codigo: '950', codigoLegado: 950, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente HIF1A', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '952', codigoLegado: 952, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell AGHBS', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '953', codigoLegado: 953, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell AGHBC', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '954', codigoLegado: 954, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente EXT 2', precoRotina: 38.0, precoPesquisa: 38.01 },
  { codigo: '955', codigoLegado: 955, categoria: 'Imunofluorescência', nome: 'IF material parafinado', precoRotina: 55.0, precoPesquisa: 55.0 },
  { codigo: '958', codigoLegado: 958, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Caldesmon', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '959', codigoLegado: 959, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Perforin', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '960', codigoLegado: 960, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL6 (E-4)', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '961', codigoLegado: 961, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente Granzyme B (EP230)', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '962', codigoLegado: 962, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IFN-y', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '963', codigoLegado: 963, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente FAS-L', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '964', codigoLegado: 964, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente SARS-CoV-2', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '965', codigoLegado: 965, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL5 ac policlonal', precoRotina: 70.0, precoPesquisa: 70.0 },
  { codigo: '966', codigoLegado: 966, categoria: 'Anticorpo', nome: 'Imuno assessoria tecnica', precoRotina: 1000.0, precoPesquisa: 1000.0 },
  { codigo: '967', codigoLegado: 967, categoria: 'Anticorpo', nome: 'Consultoria técnica presencial imuno implantação', precoRotina: 5000.0, precoPesquisa: 5000.0 },
  { codigo: '968', codigoLegado: 968, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente P501S (Prostein)', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '969', codigoLegado: 969, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell AMACR', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '970', codigoLegado: 970, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo VEGF', precoRotina: 10200.0, precoPesquisa: 10200.0 },
  { codigo: '972', codigoLegado: 972, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '973', codigoLegado: 973, categoria: 'Imunohistoquímica', nome: 'imuno com A/C do cliente IL13', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '975', codigoLegado: 975, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente PD1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '978', codigoLegado: 978, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente EC SOD', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '979', codigoLegado: 979, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente CATALASE', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '980', codigoLegado: 980, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell BHCG', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '981', codigoLegado: 981, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente UCP 1', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '982', codigoLegado: 982, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Nell-1', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '983', codigoLegado: 983, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente DNAJB9', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '984', codigoLegado: 984, categoria: 'Imunofluorescência', nome: 'IF - IGG1', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '985', codigoLegado: 985, categoria: 'Imunofluorescência', nome: 'IF - IGG2', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '986', codigoLegado: 986, categoria: 'Imunofluorescência', nome: 'IF - IGG3', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '987', codigoLegado: 987, categoria: 'Imunofluorescência', nome: 'IF - IGG4', precoRotina: 65.0, precoPesquisa: 65.0 },
  { codigo: '988', codigoLegado: 988, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente Extosina 2', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '992', codigoLegado: 992, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente PD1 AI', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '995', codigoLegado: 995, categoria: 'Outros', nome: 'teste HE ALS', precoRotina: 0.0, precoPesquisa: 0.0 },
  { codigo: '998', codigoLegado: 998, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente MYOSIN', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '999', codigoLegado: 999, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente RL90', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '1000', codigoLegado: 1000, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo CD16', precoRotina: 5400.0, precoPesquisa: 5400.0 },
  { codigo: '1001', codigoLegado: 1001, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo Calponina', precoRotina: 5400.0, precoPesquisa: 5400.0 },
  { codigo: '1002', codigoLegado: 1002, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo 34B', precoRotina: 5760.0, precoPesquisa: 5760.0 },
  { codigo: '1003', codigoLegado: 1003, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo CK5-6', precoRotina: 5040.0, precoPesquisa: 5040.0 },
  { codigo: '1004', codigoLegado: 1004, categoria: 'Anticorpo', nome: 'Imuno alíquota de BUFFER SUBSTRATE', precoRotina: 3600.0, precoPesquisa: 3600.0 },
  { codigo: '1005', codigoLegado: 1005, categoria: 'Anticorpo', nome: 'Imuno alíquota de Linker Mouse', precoRotina: 1650.0, precoPesquisa: 1650.0 },
  { codigo: '1006', codigoLegado: 1006, categoria: 'Anticorpo', nome: 'Imuno alíquota de Linker RABBIT', precoRotina: 1720.0, precoPesquisa: 1720.0 },
  { codigo: '1007', codigoLegado: 1007, categoria: 'Anticorpo', nome: 'Imuno alíquota de DAB', precoRotina: 2400.0, precoPesquisa: 2400.0 },
  { codigo: '1008', codigoLegado: 1008, categoria: 'Anticorpo', nome: 'Imuno alíquota PH BAIXO', precoRotina: 2640.0, precoPesquisa: 2640.0 },
  { codigo: '1009', codigoLegado: 1009, categoria: 'Anticorpo', nome: 'Imuno alíquota PH ALTO', precoRotina: 1060.0, precoPesquisa: 1060.0 },
  { codigo: '1011', codigoLegado: 1011, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell PTH', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '1012', codigoLegado: 1012, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Olig2', precoRotina: 140.0, precoPesquisa: 140.0 },
  { codigo: '1019', codigoLegado: 1019, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente ALFA ACTINA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '1022', codigoLegado: 1022, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell P40', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '1023', codigoLegado: 1023, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente D SMA', precoRotina: 32.0, precoPesquisa: 32.0 },
  { codigo: '1024', codigoLegado: 1024, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente TAU', precoRotina: 60.0, precoPesquisa: 60.0 },
  { codigo: '1025', codigoLegado: 1025, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C do cliente APP', precoRotina: 60.0, precoPesquisa: 60.0 },
  { codigo: '1027', codigoLegado: 1027, categoria: 'Anticorpo', nome: 'Imuno alíquota de anticorpo CD163', precoRotina: 2610.0, precoPesquisa: 2610.0 },
  { codigo: '1028', codigoLegado: 1028, categoria: 'Anticorpo', nome: 'Imuno alíquota de polimero HRP', precoRotina: 2200.0, precoPesquisa: 2200.0 },
  { codigo: '1029', codigoLegado: 1029, categoria: 'Consultoria/Serviços', nome: 'Consultoria de reciclagem técnica', precoRotina: 5000.0, precoPesquisa: 5000.0 },
  { codigo: '1030', codigoLegado: 1030, categoria: 'Imunohistoquímica', nome: 'Imunohistoquimica painel 4 marcadores', precoRotina: 240.0, precoPesquisa: 240.0 },
  { codigo: '1034', codigoLegado: 1034, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell Bcl 10', precoRotina: 85.0, precoPesquisa: 85.0 },
  { codigo: '1037', codigoLegado: 1037, categoria: 'Imunohistoquímica', nome: 'Imuno com A/C Histocell CD 16', precoRotina: 85.0, precoPesquisa: 85.0 },
] as const;